# PN5180 with on_tag Trigger - Complete Example
# This demonstrates all the new features including on_tag automation triggers

esphome:
  name: pn5180-with-automation
  friendly_name: "PN5180 with Automations"
  
  libraries:
    - SPI
    - PN5180_LIBRARY=https://github.com/ATrappmann/PN5180-Library.git#master

esp32:
  board: esp32dev
  framework:
    type: arduino

logger:
  level: DEBUG

api:
  encryption:
    key: !secret api_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  
  ap:
    ssid: "PN5180-Automation"
    password: "configure"

# External component with all new features
external_components:
  - source:
      type: git
      url: https://github.com/johnmclear/esphome_pn5180
    refresh: 0s

# ===================================================================
# PN5180 NFC Reader with on_tag triggers
# ===================================================================
text_sensor:
  - platform: pn5180
    name: "NFC Tag"
    id: nfc_reader
    cs_pin: GPIO16
    busy_pin: GPIO5
    rst_pin: GPIO17
    update_interval: 500ms
    
    # â­ NEW: on_tag trigger - fires when a new tag is detected
    on_tag:
      then:
        # Log the tag
        - logger.log:
            format: "New tag detected: %s"
            args: ['tag_id.c_str()']
            level: INFO
        
        # Flash LED to indicate scan
        - light.turn_on:
            id: status_led
            brightness: 100%
            red: 0%
            green: 100%
            blue: 0%
            flash_length: 500ms
        
        # Send event to Home Assistant
        - homeassistant.event:
            event: esphome.nfc_tag_scanned
            data:
              reader: "front_door"
              tag_id: !lambda 'return tag_id;'
              timestamp: !lambda 'return id(ha_time).now().timestamp;'
        
        # Play a beep sound (if you have a buzzer)
        - rtttl.play: "success:d=4,o=5,b=100:16e6,16e6"
        
        # Store last scan time
        - globals.set:
            id: last_scan_time
            value: !lambda 'return id(ha_time).now().timestamp;'
        
        # Check against known tags
        - if:
            condition:
              lambda: 'return tag_id == "E0 07 01 23 45 67 89 AB";'
            then:
              # This is John's tag
              - logger.log: "Welcome home, John!"
              - homeassistant.service:
                  service: script.user_arrived
                  data:
                    user: "john"
            else:
              # Unknown tag
              - logger.log: "Unknown tag detected"
              - light.turn_on:
                  id: status_led
                  brightness: 100%
                  red: 100%
                  green: 0%
                  blue: 0%
                  flash_length: 1s

# ===================================================================
# Additional sensors for monitoring
# ===================================================================
sensor:
  - platform: uptime
    name: "Uptime"
    id: uptime_sensor

  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s

  # Template sensor for time since last scan
  - platform: template
    name: "Time Since Last Scan"
    id: time_since_scan
    lambda: |-
      if (id(last_scan_time) == 0) {
        return NAN;
      }
      return (id(ha_time).now().timestamp - id(last_scan_time)) / 60.0;
    unit_of_measurement: "min"
    accuracy_decimals: 1
    update_interval: 10s

# ===================================================================
# Status LED (RGB)
# ===================================================================
light:
  - platform: rgb
    name: "Status LED"
    id: status_led
    red: status_led_red
    green: status_led_green
    blue: status_led_blue
    effects:
      - pulse:
          name: "Pulse"
          transition_length: 1s
          update_interval: 1s

output:
  - platform: ledc
    pin: GPIO25
    id: status_led_red
  
  - platform: ledc
    pin: GPIO26
    id: status_led_green
  
  - platform: ledc
    pin: GPIO27
    id: status_led_blue

# ===================================================================
# Buzzer for audio feedback (optional)
# ===================================================================
output:
  - platform: ledc
    pin: GPIO22
    id: buzzer_output

rtttl:
  output: buzzer_output

# ===================================================================
# Time component for timestamps
# ===================================================================
time:
  - platform: homeassistant
    id: ha_time

# ===================================================================
# Global variables
# ===================================================================
globals:
  # Store last scan timestamp
  - id: last_scan_time
    type: long
    restore_value: no
    initial_value: '0'
  
  # Count total scans
  - id: scan_count
    type: int
    restore_value: yes
    initial_value: '0'

# ===================================================================
# Binary sensors
# ===================================================================
binary_sensor:
  - platform: status
    name: "Status"

# ===================================================================
# Buttons for manual control
# ===================================================================
button:
  - platform: restart
    name: "Restart"
  
  - platform: template
    name: "Reset Scan Counter"
    on_press:
      then:
        - lambda: 'id(scan_count) = 0;'
        - logger.log: "Scan counter reset"

# ===================================================================
# Additional text sensors
# ===================================================================
text_sensor:
  - platform: wifi_info
    ip_address:
      name: "IP Address"
    ssid:
      name: "Connected SSID"

  # Last scanned tag (stored separately)
  - platform: template
    name: "Last Tag"
    id: last_tag
    icon: "mdi:nfc-variant"

# ===================================================================
# Intervals for periodic tasks
# ===================================================================
interval:
  - interval: 60s
    then:
      - logger.log:
          format: "Status: %d scans, uptime %us"
          args:
            - 'id(scan_count)'
            - '(unsigned int)id(uptime_sensor).state'

# ===================================================================
# Example Home Assistant Automations
# ===================================================================

# To use in Home Assistant automations.yaml:
#
# - alias: "NFC Tag Scanned - Turn on lights"
#   trigger:
#     - platform: event
#       event_type: esphome.nfc_tag_scanned
#       event_data:
#         reader: "front_door"
#         tag_id: "E0 07 01 23 45 67 89 AB"
#   action:
#     - service: light.turn_on
#       target:
#         entity_id: light.living_room
#
# - alias: "Unknown NFC Tag - Send notification"
#   trigger:
#     - platform: event
#       event_type: esphome.nfc_tag_scanned
#   condition:
#     - condition: template
#       value_template: >
#         {{ trigger.event.data.tag_id not in [
#           'E0 07 01 23 45 67 89 AB',
#           'A0 B0 C0 D0 E0 F0 00 11'
#         ] }}
#   action:
#     - service: notify.mobile_app
#       data:
#         title: "Unknown NFC Tag"
#         message: "Tag {{ trigger.event.data.tag_id }} scanned at {{ trigger.event.data.reader }}"

# ===================================================================
# Usage Examples
# ===================================================================

# Example 1: Door Access Control
# When John's tag is scanned, unlock the door and log entry

# Example 2: Presence Detection
# Different family members have different tags
# Track who's home based on tag scans

# Example 3: Task Triggers
# Scan a tag to start/stop a task
# E.g., "Start cleaning" tag, "Done cleaning" tag

# Example 4: Scene Control
# Different tags activate different scenes
# "Movie night" tag, "Bedtime" tag, etc.

# Example 5: Inventory Tracking
# Tag items in your home
# Log when items are moved or used
