# PN5180 Component - Proper ESPHome Structure
# This uses pn5180 as its own platform (like rc522, pn532)

esphome:
  name: pn5180-proper
  friendly_name: "PN5180 NFC Reader"
  
  libraries:
    - SPI
    - PN5180_LIBRARY=https://github.com/ATrappmann/PN5180-Library.git#master

esp32:
  board: esp32dev
  framework:
    type: arduino

logger:
  level: DEBUG

api:
  encryption:
    key: !secret api_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  
  ap:
    ssid: "PN5180-Fallback"
    password: "configure"

# External component
external_components:
  - source:
      type: git
      url: https://github.com/johnmclear/esphome_pn5180
    refresh: 0s

# ===================================================================
# SPI Configuration (required for PN5180)
# ===================================================================
spi:
  clk_pin: GPIO18
  miso_pin: GPIO19
  mosi_pin: GPIO23

# ===================================================================
# PN5180 Component - Now its own platform!
# ===================================================================
pn5180:
  cs_pin: GPIO16      # SPI chip select
  busy_pin: GPIO5     # PN5180 busy signal
  rst_pin: GPIO17     # PN5180 reset pin
  update_interval: 500ms
  
  # ⭐ on_tag trigger - fires when a new tag is detected
  on_tag:
    then:
      # Log the tag
      - logger.log:
          format: "Tag scanned: %s"
          args: ['tag_id.c_str()']
      
      # Flash LED
      - light.turn_on:
          id: status_led
          brightness: 100%
          flash_length: 500ms
      
      # Send to Home Assistant
      - homeassistant.event:
          event: esphome.nfc_tag_scanned
          data:
            tag_id: !lambda 'return tag_id;'
            location: "front_door"

# ===================================================================
# Status LED
# ===================================================================
light:
  - platform: status_led
    name: "Status LED"
    id: status_led
    pin: GPIO2

# ===================================================================
# Additional sensors
# ===================================================================
sensor:
  - platform: uptime
    name: "Uptime"

  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "IP Address"

binary_sensor:
  - platform: status
    name: "Status"

button:
  - platform: restart
    name: "Restart"

# ===================================================================
# Example Automation Scenarios
# ===================================================================

# Scenario 1: Door Access - Multiple users
# pn5180:
#   on_tag:
#     - if:
#         condition:
#           lambda: 'return tag_id == "E0 07 01 23 45 67 89 AB";'
#         then:
#           - logger.log: "Welcome John!"
#           - homeassistant.service:
#               service: lock.unlock
#               data:
#                 entity_id: lock.front_door
#     - if:
#         condition:
#           lambda: 'return tag_id == "A0 B0 C0 D0 E0 F0 00 11";'
#         then:
#           - logger.log: "Welcome Jane!"
#           - homeassistant.service:
#               service: lock.unlock
#               data:
#                 entity_id: lock.front_door

# Scenario 2: Scene Control
# pn5180:
#   on_tag:
#     - if:
#         condition:
#           lambda: 'return tag_id == "10 20 30 40 50 60 70 80";'
#         then:
#           - homeassistant.service:
#               service: scene.turn_on
#               data:
#                 entity_id: scene.movie_night

# Scenario 3: Presence Detection
# pn5180:
#   on_tag:
#     - homeassistant.tag_scanned: !lambda 'return tag_id;'
