esphome:
  name: pn5180
  libraries:
    - SPI
    - PN5180_LIBRARY=https://github.com/ATrappmann/PN5180-Library.git#master

esp32:
  board: esp32dev
  framework:
    type: arduino

logger:
  level: DEBUG

api:
ota:
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:

external_components:
  - source:
      type: git
      url: https://github.com/johnmclear/esphome_pn5180
      ref: claude
    refresh: 0s

spi:
  clk_pin: GPIO18
  miso_pin: GPIO19
  mosi_pin: GPIO23

# ─── Main PN5180 component ────────────────────────────────────────────────────
pn5180:
  cs_pin: GPIO16
  busy_pin: GPIO5
  rst_pin: GPIO17
  update_interval: 500ms

  # Health check
  health_check_enabled: true
  health_check_interval: 60s
  max_failed_checks: 3
  auto_reset_on_failure: true

  # Fires when any new tag is detected - tag_id is available as variable
  on_tag:
    then:
      - logger.log:
          format: "Tag detected: %s"
          args: ['tag_id.c_str()']
      # Native Home Assistant tag integration
      - homeassistant.tag_scanned: !lambda 'return tag_id;'

  # Fires when tag is removed - tag_id is the tag that was just removed
  on_tag_removed:
    then:
      - logger.log:
          format: "Tag removed: %s"
          args: ['tag_id.c_str()']


# ─── Binary sensors for known tags ───────────────────────────────────────────
binary_sensor:
  - platform: pn5180
    name: "John's Badge"
    uid: "E0 07 01 23 45 67 89 AB"

  - platform: pn5180
    name: "Jane's Badge"
    uid: "A0 B0 C0 D0 E0 F0 00 11"

  - platform: pn5180
    name: "Guest Badge"
    uid: "11 22 33 44 55 66 77 88"


# ─── Text sensor for last scanned tag ────────────────────────────────────────
text_sensor:
  - platform: pn5180
    name: "Last NFC Tag"
